### ISSUE TITLE
Forces Adalogger M0 into bootloader mode

### ISSUE THREAD

**Issue by treychaffin** [adafruit/Adafruit-Power-Relay-FeatherWing-PCB#1]
I am using the Power Relay FeatherWing stacked on top of a Feather M0 Adalogger. I have a 120 VAC, 13 watt incandescent lightbulb connected to the normally side of the relay. I have the relay set up to be triggered with the A1 pin on the Adalogger. I'm using a simple arduino sketch to toggle the relay using Serial.read and keyboard commands. Toggling the relay will randomly (every 2-6 toggles) send the Adalogger into bootloader mode, it doesn't seem to matter whether or not the relay is being toggled on or off. When no load is attached to the relay, the relay functions correctly and doesn't randomly send the Adalogger into bootloader mode.

I've used a variety of lightbulbs, incandescants, CFLs, and LEDs, all of which this problem is repeatable. I've tried using spare relay and Adalogger modules, the problem is still repeatable.

**Comment by ladyada** [comment]
hiya, questions about how to use adafruit products are best posted in the adafruit forums  at [forums.adafruit.com](forums.adafruit.com/)
thats where tech support is handled - github issues are where folks can issue bug reports (e.g. something that ought to work but doesnt due to a hardware or software bug)

thanks! :)
